### ISSUE TITLE
Alerta de eventos

### ISSUE THREAD

**Issue by wesmelo** [wesmelo/femugPE-bot#9]
Criar comando para avisar ao grupo quando houver novos eventos.

Pode ser realizado a abertura de um repositório no [github do FEMUG-PE](https://github.com/FEMUGPE), semelhante ao do [frontendbr](https://github.com/frontendbr/eventos) com os eventos que irão acontecer, como o FEMUG, GeekNight, Encontro PyLadies. 

Atualmente temos a função `/jobs` no bot que retorna a lista de vagas abertas no frontendbr direcionadas para o Recife

**Comment by higordiego** [comment]
Seria uma boa mesmo, mas consegue criar o issues que organizo o robot para pegar...

**Comment by wesmelo** [comment]
to vendo com o pessoal da organização pra saber como posso implementar isso la e organizar tudo em um lugar só

**Comment by wesmelo** [comment]
melhoria implementada pelo @higordiego , valeu mesmo pela contribuição!

Mais em frente, estaremos direcionando para um novo repositório de eventos com mais novidades 👊
